"""Add local_profiles and user_locations tables

Revision ID: 3dda9c1e9498
Revises: c01c65dfccdf
Create Date: 2025-09-11 21:47:03.431654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dda9c1e9498'
down_revision: Union[str, Sequence[str], None] = 'c01c65dfccdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_notifications_user_id_unread'), table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_table('notifications')
    op.drop_table('itinerary_proposals')
    op.drop_table('search_history')
    op.drop_index(op.f('idx_conversations_last_message'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_participants'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('search_preferences')
    op.drop_index(op.f('idx_itinerary_requests_location_dates'), table_name='itinerary_requests')
    op.drop_table('itinerary_requests')
    op.drop_index(op.f('idx_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_created_at'), table_name='messages')
    op.drop_index(op.f('idx_messages_sender'), table_name='messages')
    op.drop_index(op.f('idx_messages_unread'), table_name='messages', postgresql_where='(is_read = false)')
    op.drop_table('messages')
    op.drop_index(op.f('idx_itinerary_templates_search'), table_name='itinerary_templates', postgresql_using='gin')
    op.drop_table('itinerary_templates')
    op.drop_index(op.f('idx_reviews_rating'), table_name='reviews')
    op.drop_table('reviews')
    op.add_column('local_profiles', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('local_profiles', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('local_profiles', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('local_profiles', sa.Column('expertise_areas', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('local_profiles', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('local_profiles', sa.Column('max_group_size', sa.Integer(), nullable=True))
    op.add_column('local_profiles', sa.Column('verification_documents', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('local_profiles', sa.Column('background_check_status', sa.String(length=50), nullable=True))
    op.add_column('local_profiles', sa.Column('base_hourly_rate', sa.Float(), nullable=True))
    op.add_column('local_profiles', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('local_profiles', sa.Column('services_offered', sa.Text(), nullable=True))
    op.add_column('local_profiles', sa.Column('home_city', sa.String(length=255), nullable=False))
    op.add_column('local_profiles', sa.Column('home_country', sa.String(length=255), nullable=False))
    op.add_column('local_profiles', sa.Column('travel_radius_km', sa.Integer(), nullable=True))
    op.add_column('local_profiles', sa.Column('total_bookings', sa.Integer(), nullable=True))
    op.add_column('local_profiles', sa.Column('response_rate_percent', sa.Integer(), nullable=True))
    op.add_column('local_profiles', sa.Column('fun_fact', sa.Text(), nullable=True))
    op.add_column('local_profiles', sa.Column('why_local_guide', sa.Text(), nullable=True))
    op.add_column('local_profiles', sa.Column('instagram_handle', sa.String(length=100), nullable=True))
    op.add_column('local_profiles', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.alter_column('local_profiles', 'languages',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("ARRAY['en'::text]"))
    op.alter_column('local_profiles', 'average_rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_local_profiles_availability'), table_name='local_profiles')
    op.create_unique_constraint(None, 'local_profiles', ['user_id'])
    op.create_foreign_key(None, 'local_profiles', 'profiles', ['user_id'], ['id'])
    op.drop_column('local_profiles', 'total_completed_itineraries')
    op.drop_column('local_profiles', 'total_conversations')
    op.drop_column('local_profiles', 'specialties')
    op.drop_column('local_profiles', 'availability_status')
    op.add_column('profiles', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('languages_spoken', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('profiles', sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('profiles', sa.Column('travel_style', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('emergency_contact_name', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('profile_visibility', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('show_age', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('show_location', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('profiles_email_key'), 'profiles', type_='unique')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.add_column('user_locations', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('user_locations', sa.Column('address', sa.String(length=500), nullable=False))
    op.add_column('user_locations', sa.Column('state_province', sa.String(length=255), nullable=True))
    op.add_column('user_locations', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('user_locations', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('user_locations', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('user_locations', sa.Column('place_type', sa.String(length=100), nullable=True))
    op.add_column('user_locations', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('user_locations', sa.Column('arrival_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_locations', sa.Column('departure_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_locations', sa.Column('is_temporary', sa.Boolean(), nullable=True))
    op.add_column('user_locations', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('user_locations', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('user_locations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('user_locations', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user_locations', 'country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_user_locations_city_country'), table_name='user_locations')
    op.drop_index(op.f('idx_user_locations_coordinates'), table_name='user_locations', postgresql_using='gist')
    op.drop_index(op.f('idx_user_locations_user_id'), table_name='user_locations')
    op.create_foreign_key(None, 'user_locations', 'profiles', ['user_id'], ['id'])
    op.drop_column('user_locations', 'country_code')
    op.drop_column('user_locations', 'coordinates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locations', sa.Column('coordinates', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('user_locations', sa.Column('country_code', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_locations', type_='foreignkey')
    op.create_index(op.f('idx_user_locations_user_id'), 'user_locations', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_locations_coordinates'), 'user_locations', ['coordinates'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_user_locations_city_country'), 'user_locations', ['city', 'country'], unique=False)
    op.alter_column('user_locations', 'country',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_locations', 'city',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('user_locations', 'updated_at')
    op.drop_column('user_locations', 'timezone')
    op.drop_column('user_locations', 'notes')
    op.drop_column('user_locations', 'is_temporary')
    op.drop_column('user_locations', 'departure_date')
    op.drop_column('user_locations', 'arrival_date')
    op.drop_column('user_locations', 'is_public')
    op.drop_column('user_locations', 'place_type')
    op.drop_column('user_locations', 'longitude')
    op.drop_column('user_locations', 'latitude')
    op.drop_column('user_locations', 'postal_code')
    op.drop_column('user_locations', 'state_province')
    op.drop_column('user_locations', 'address')
    op.drop_column('user_locations', 'name')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=False)
    op.create_unique_constraint(op.f('profiles_email_key'), 'profiles', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('profiles', 'show_location')
    op.drop_column('profiles', 'show_age')
    op.drop_column('profiles', 'profile_visibility')
    op.drop_column('profiles', 'emergency_contact_phone')
    op.drop_column('profiles', 'emergency_contact_name')
    op.drop_column('profiles', 'is_phone_verified')
    op.drop_column('profiles', 'is_email_verified')
    op.drop_column('profiles', 'travel_style')
    op.drop_column('profiles', 'interests')
    op.drop_column('profiles', 'languages_spoken')
    op.drop_column('profiles', 'nationality')
    op.drop_column('profiles', 'date_of_birth')
    op.drop_column('profiles', 'phone_number')
    op.add_column('local_profiles', sa.Column('availability_status', postgresql.ENUM('available', 'busy', 'away', 'offline', name='availability_enum'), server_default=sa.text("'available'::availability_enum"), autoincrement=False, nullable=True))
    op.add_column('local_profiles', sa.Column('specialties', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('local_profiles', sa.Column('total_conversations', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('local_profiles', sa.Column('total_completed_itineraries', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'local_profiles', type_='foreignkey')
    op.drop_constraint(None, 'local_profiles', type_='unique')
    op.create_index(op.f('idx_local_profiles_availability'), 'local_profiles', ['availability_status'], unique=False)
    op.alter_column('local_profiles', 'average_rating',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('local_profiles', 'languages',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("ARRAY['en'::text]"))
    op.drop_column('local_profiles', 'website_url')
    op.drop_column('local_profiles', 'instagram_handle')
    op.drop_column('local_profiles', 'why_local_guide')
    op.drop_column('local_profiles', 'fun_fact')
    op.drop_column('local_profiles', 'response_rate_percent')
    op.drop_column('local_profiles', 'total_bookings')
    op.drop_column('local_profiles', 'travel_radius_km')
    op.drop_column('local_profiles', 'home_country')
    op.drop_column('local_profiles', 'home_city')
    op.drop_column('local_profiles', 'services_offered')
    op.drop_column('local_profiles', 'currency')
    op.drop_column('local_profiles', 'base_hourly_rate')
    op.drop_column('local_profiles', 'background_check_status')
    op.drop_column('local_profiles', 'verification_documents')
    op.drop_column('local_profiles', 'max_group_size')
    op.drop_column('local_profiles', 'is_available')
    op.drop_column('local_profiles', 'expertise_areas')
    op.drop_column('local_profiles', 'description')
    op.drop_column('local_profiles', 'title')
    op.drop_column('local_profiles', 'user_id')
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('traveler_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('local_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('helpful_votes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('response_from_local', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('reviews_rating_check')),
    sa.ForeignKeyConstraint(['request_id'], ['itinerary_requests.id'], name=op.f('reviews_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey')),
    sa.UniqueConstraint('traveler_id', 'local_id', 'request_id', name=op.f('unique_review'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_reviews_rating'), 'reviews', ['local_id', 'rating'], unique=False)
    op.create_table('itinerary_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('local_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('itinerary_templates_pkey'))
    )
    op.create_index(op.f('idx_itinerary_templates_search'), 'itinerary_templates', [sa.literal_column("to_tsvector('english'::regconfig, (title || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_type', postgresql.ENUM('text', 'image', 'location', 'system', name='message_type_enum'), server_default=sa.text("'text'::message_type_enum"), autoincrement=False, nullable=True),
    sa.Column('attachment_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('idx_messages_unread'), 'messages', ['conversation_id'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('idx_messages_sender'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_messages_created_at'), 'messages', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('itinerary_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('traveler_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('local_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('group_size', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('preferences', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('special_requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'in_progress', 'completed', 'declined', 'cancelled', name='request_status_enum'), server_default=sa.text("'pending'::request_status_enum"), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('group_size > 0', name='valid_group_size'),
    sa.CheckConstraint('start_date <= end_date', name='valid_dates'),
    sa.CheckConstraint('start_date >= CURRENT_DATE', name='future_dates'),
    sa.PrimaryKeyConstraint('id', name='itinerary_requests_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_itinerary_requests_location_dates'), 'itinerary_requests', ['start_date', 'end_date'], unique=False)
    op.create_table('search_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('preferred_languages', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('preferred_age_range', postgresql.INT4RANGE(), autoincrement=False, nullable=True),
    sa.Column('max_response_time_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferred_specialties', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('search_preferences_pkey'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('traveler_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('local_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'archived', 'blocked', 'deleted', name='conversation_status_enum'), server_default=sa.text("'active'::conversation_status_enum"), autoincrement=False, nullable=True),
    sa.Column('message_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('traveler_id <> local_id', name=op.f('different_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey')),
    sa.UniqueConstraint('traveler_id', 'local_id', name=op.f('unique_conversation'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_conversations_participants'), 'conversations', ['traveler_id', 'local_id'], unique=False)
    op.create_index(op.f('idx_conversations_last_message'), 'conversations', [sa.literal_column('last_message_at DESC')], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicked_profile_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('search_history_pkey'))
    )
    op.create_table('itinerary_proposals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('revision_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['itinerary_requests.id'], name=op.f('itinerary_proposals_request_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('itinerary_proposals_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('new_message', 'itinerary_request', 'request_accepted', 'request_completed', 'new_review', name='notification_type_enum'), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_pushed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('idx_notifications_user_id_unread'), 'notifications', ['user_id'], unique=False, postgresql_where='(is_read = false)')
    # ### end Alembic commands ###
